### ISSUE TITLE
L_ctermid undeclared

### ISSUE THREAD

**Issue by ajusa** [Yardanico/cosmonim#1]
Hello,
I tried using cosmonim to compile a command line project, but I got this error:
```
/home/ajusa/.cache/nim/main_r/stdlib_terminal.nim.c: In function ‘terminalWidth__s9bdJLFVciGfQ0i2sQaMF1g’:
/home/ajusa/.cache/nim/main_r/stdlib_terminal.nim.c:204:28: error: ‘L_ctermid’ undeclared (first use in this function)
  204 |  cterm = mnewString(((NI) (L_ctermid)));
```
My guess this is related to an OS level binding for which terminal this code is being compiled for. 

https://github.com/nim-lang/Nim/blob/9819fb21d8db818c0b3027d4e6ba58dc550b77c0/lib/pure/terminal.nim#L241 appears to be the terminal code.

My nim version is 
```
Nim Compiler Version 1.4.4 [Linux: amd64]
Compiled at 2021-02-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2ff517462bf8609b30e6134c96658aa7912b628a
active boot switches: -d:release
```
Let me know if you need any more information!

**Comment by ajusa** [comment]
https://github.com/jart/cosmopolitan/blob/master/libc/stdio/stdio.h might be pertinent, as there is no `L_ctermid` defined in there.

**Comment by ajusa** [comment]
Just as an update, tried it with Cosmopolitan 0.3 and it still doesn't compile for the same reason.

**Comment by ajusa** [comment]
Well I just went ahead and manually defined it in stdio.h within the stubs, it compiles at least
```
#define L_ctermid 100
```

**Comment by Yardanico** [comment]
If anyone is reading this issue - Cosmopolitan seems to define `L_ctermid` nowadays, so you don't need to manually apply this fix.

**Comment by ajusa** [comment]
Yes, it does now! I spent some time with jart, debugging it in the
cosmopolitan Discord server to get it added.
